#!/bin/bash -l
#SBATCH --job-name="task6_V2"
#SBATCH --account="c24"
#SBATCH --mail-type=ALL
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=normal
#SBATCH --constraint=gpu
#SBATCH --hint=nomultithread
#SBATCH --error=/users/msalvado/prova_transfpytorch/task6_V2_mult3/error_flags_ContTrans_nnodes1_ntasksxnode1_procgpu.txt
#SBATCH --output=/users/msalvado/prova_transfpytorch/task6_V2_mult3/ContTrans_nnodes1_ntasksxnode1_procgpu.txt

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export PYTHONUNBUFFERED=true

RUNPATH=/users/msalvado/prova_transfpytorch/task6_V2_mult3/src/
conda activate MLT3
cd $RUNPATH

srun python3 -u main.py
